---
name: Heapviz tool tests
on:
  push:
    paths:
      - 'tools/heapviz/**'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  cbor_test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Check heapviz tool
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --manifest-path tool/heapviz/Cargo.toml

      - name: Unit testing of heapviz tool (debug mode)
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path tool/heapviz/Cargo.toml

      - name: Unit testing of heapviz tool (release mode)
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path tool/heapviz/Cargo.toml --release
